/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_project_mystudyproject_jni_study_JniTools */

#ifndef _Included_com_project_mystudyproject_jni_study_JniTools
#define _Included_com_project_mystudyproject_jni_study_JniTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_project_mystudyproject_jni_study_JniTools
 * Method:    getStringFromNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_project_mystudyproject_jni_1study_JniTools_getStringFromNDK
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
